version: "3.9"
services:
  interface:
    container_name: interface
    build: ./ssh-interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    environments:
      PORT: 3001
